services:
  frontend:
    build:
      context: .
      dockerfile: DockerFile
      args:
        BASE_HREF: /
    container_name: sipresidencia-frontend
    ports:
      - "8094:80"
    restart: always
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
    container_name: sipresidencia-backend
    ports:
      - "3044:3050"
    env_file:
      - ./backend/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
